version: '2'
services:
  mysql:
    build: ./mysql
    ports:
     - '9990:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '8910:80'
    volumes:
      - ./html:/var/www/html
      - ./apache:/etc/apache2/sites-available
volumes:
  db:
