version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "11112:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: results
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  php:
    build: ./php
    ports:
      - '8910:80'
    volumes:
      - /Users/jchai/www/revelist:/var/www/html
      - ./apache:/etc/apache2/sites-available

volumes:
  db_data:
  
